 name 			= "Subsume"; // Name of your mod
 author 		= "Deebs, Tally"; // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "Deebs_Pic.jpg"; // Logo displayed in the main menu
 logoOver 		= "Deebs_Pic.jpg"; // When the mouse is over, in the main menu
 tooltip 		= "Subsume";
 tooltipOwned 	= "credit_mod"; // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "Possession_Img.jpg"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName 	= "Discord";
 action 		= "https://discord.gg/bRTqWJzeza"; // Website URL, that can be accessed from the expansions menu
 overview 		= "A mod that works allows for any unit to be taken over by the player in both SP and MP"; // Supports structured text
 hideName 		= 0; // Hide the extension name
 hidePicture	= 0;	// Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "Deebs_Pic.jpg"; // Display in creative lists, next to the entities added by the mod